name: sa2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy=1.24.4
  - pandas=2.0.3
  - pillow=10.3.0
  - scipy=1.10.1
  - matplotlib=3.7.3
  - scikit-learn=1.3.2
  - scikit-image=0.19.3
  - opencv=4.9.0
  - pyparsing=3.1.2
  - pytorch
  - simpleitk=2.3.1
  - nibabel=5.2.1
  - pip=24.0
  - torchvision
  - supervision=0.19.0
  - pip:
    - segment-anything==1.0 
    - transformers==4.39.3
    - streamlit==1.33.0 
    - streamlit-image-select==0.6.0
    - streamlit-drawable-canvas==0.9.3
    - streamlit-image-comparison==0.0.4
    - streamlit-cropper==0.2.2
    - streamlit_extras==0.4.2